<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyVersion>67.0.0.0</AssemblyVersion>
    <FileVersion>67.0.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Magic.BrowserAutomationNET\Magic.BrowserAutomationNET.csproj" />
  </ItemGroup>

</Project>
